### ISSUE TITLE
Footer has strange break with varying window sizes

### ISSUE THREAD

**Issue by jliphard** [enyalabs/FeverIQ#41]
<img width="581" alt="Screen Shot 2020-05-03 at 8 17 29 AM" src="https://user-images.githubusercontent.com/10926168/80917936-f2c4c480-8d16-11ea-8a35-65fc31583893.png">
<img width="494" alt="Screen Shot 2020-05-03 at 8 16 50 AM" src="https://user-images.githubusercontent.com/10926168/80917940-f5271e80-8d16-11ea-98e8-d32b5eccc517.png">
<img width="695" alt="Screen Shot 2020-05-03 at 8 16 44 AM" src="https://user-images.githubusercontent.com/10926168/80917943-f7897880-8d16-11ea-9d17-b51ad416ea93.png">

**Comment by ankitr** [comment]
@jliphard I can't replicate the middle condition. Currently I styled it to break into the copyright above the Built by and links in some screen conditions but I am happy to change it.
